---
version: '3.8'

networks:
  mcp-net:

services:
  mcp-server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: mcp-server
    ports:
      - "8000:8000"
    volumes:
      - ./network_share:/data/network_share
    env_file:
      - .env
    networks:
      - mcp-net