---
version: '3.8'

networks:
  mcp-net:

services:
  mcp-server:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        SERVICENOW_USERNAME: ${SERVICENOW_USERNAME}
        SERVICENOW_PASSWORD: ${SERVICENOW_PASSWORD}
        SERVICE_MANAGER_API_URL: ${SERVICE_MANAGER_API_URL}
        DATABASE_URL: ${DATABASE_URL}
    container_name: mcp_server
    ports:
      - "8000:8000"
    environment:
      - SERVICE_MANAGER_API_URL=${SERVICE_MANAGER_API_URL}
      - SERVICENOW_USERNAME=${SERVICENOW_USERNAME}
      - SERVICENOW_PASSWORD=${SERVICENOW_PASSWORD}
      - GLPI_API_URL=http://mock_glpi_api:8081/glpi/apirest.php
      - GLPI_APP_TOKEN=${GLPI_APP_TOKEN}
      - GLPI_USERNAME=${GLPI_USERNAME}
      - GLPI_PASSWORD=${GLPI_PASSWORD}
      - GLPI_ACCESS_TOKEN=${GLPI_ACCESS_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - mcp-net
    depends_on:
      - mock-servicenow-api
      - mock-glpi-api

  mock-servicenow-api:
    build:
      context: ../mock_servicenow_api
      dockerfile: Dockerfile
    container_name: mock_servicenow_api
    ports:
      - "5000:5000"
    networks:
      - mcp-net

  mock-glpi-api:
    build:
      context: ../mock_glpi_api
      dockerfile: Dockerfile
    container_name: mock_glpi_api
    ports:
      - "8081:8081"
    networks:
      - mcp-net
