apiVersion: v1
kind: Namespace
metadata:
  name: wazuh-tools
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-tools-config
  namespace: wazuh-tools
data:
  WAZUH_URL: "https://10.2.0.149:55000"
  WAZUH_SSL_VERIFY: "False"
---
apiVersion: v1
kind: Secret
metadata:
  name: wazuh-tools-secret
  namespace: wazuh-tools
type: Opaque
data:
  WAZUH_USER: d2F6dWg=
  WAZUH_PASSWORD: cUYyKm5iT09OTDhpOHQrc3YwS05EYVBPWEY5RU1STko=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-tools-deployment
  namespace: wazuh-tools
  labels:
    app: wazuh-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-tools
  template:
    metadata:
      labels:
        app: wazuh-tools
    spec:
      containers:
      - name: wazuh-tools
        image: antuelle78/wazuh_tools:latest
        ports:
        - containerPort: 8005
        env:
        - name: WAZUH_URL
          valueFrom:
            configMapKeyRef:
              name: wazuh-tools-config
              key: WAZUH_URL
        - name: WAZUH_USER
          valueFrom:
            secretKeyRef:
              name: wazuh-tools-secret
              key: WAZUH_USER
        - name: WAZUH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wazuh-tools-secret
              key: WAZUH_PASSWORD
        - name: WAZUH_SSL_VERIFY
          valueFrom:
            configMapKeyRef:
              name: wazuh-tools-config
              key: WAZUH_SSL_VERIFY
---
apiVersion: v1
kind: Service
metadata:
  name: wazuh-tools-service
  namespace: wazuh-tools
spec:
  type: NodePort
  selector:
    app: wazuh-tools
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
      nodePort: 30085